### ISSUE TITLE
Not working on iPadOS 18.1

### ISSUE THREAD

**Issue by GoldenMelky** [leminlimez/Nugget#135]
After updating my ipad to 18.1 I can't apply changes anymore, it's giving me this error:
```Traceback (most recent call last):
  File "/home/golden/Nugget/devicemanagement/device_manager.py", line 175, in apply_changes
    restore_files(files=files_to_restore, reboot=True, lockdown_client=self.data_singleton.current_device.ld)
  File "/home/golden/Nugget/Sparserestore/restore.py", line 53, in restore_files
    perform_restore(backup=back, reboot=reboot, lockdown_client=lockdown_client)
  File "/home/golden/Nugget/Sparserestore/__init__.py", line 27, in perform_restore
    raise e
  File "/home/golden/Nugget/Sparserestore/__init__.py", line 20, in perform_restore
    mb.restore(backup_dir, system=True, reboot=False, copy=False, source=".")
  File "/home/golden/.local/lib/python3.10/site-packages/pymobiledevice3/services/mobilebackup2.py", line 140, in restore
    dl.dl_loop(progress_callback)
  File "/home/golden/.local/lib/python3.10/site-packages/pymobiledevice3/services/device_link.py", line 61, in dl_loop
    raise PyMobileDevice3Exception(f'Device link error: {message[1]}')
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Domain name cannot contain a slash (MBErrorDomain/205)', 'MessageName': 'Response'}

**Comment by leminlimez** [comment]
please include nugget version and what tweaks you were applying

**Comment by reedary** [comment]
My iPad is 18.1 is ok, but 18.1beta2 is not ok
