### ISSUE TITLE
Couldn't apply changes on iPhone 13 pro max iOS 18.1

### ISSUE THREAD

**Issue by ZieadEmad** [leminlimez/Nugget#163]
Traceback (most recent call last):
  File "devicemanagement/device_manager.py", line 327, in apply_changes
  File "Sparserestore/restore.py", line 105, in restore_files
  File "Sparserestore/__init__.py", line 36, in perform_restore
  File "Sparserestore/__init__.py", line 27, in perform_restore
  File "pymobiledevice3/services/mobilebackup2.py", line 140, in restore
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 1, 'ErrorDescription': 'Error setting WillEncrypt value in lockdown (MBErrorDomain/1). Underlying error: Cannot remove iTunes Backup Encryption - Encrypted Backup MDM setting present on device (MBErrorDomain/22).', 'MessageName': 'Response'}

**Comment by Knightsepig** [comment]
I am experiencing a similar problem.

**Comment by leminlimez** [comment]
Nugget cannot be used on your device.

Your device is managed and MDM backup encryption is on. This must be turned off in order for Nugget to work. Please do not use Nugget on your school/work device.
