### ISSUE TITLE
pymobiledevice3.exceptions.ConnectionTerminatedError

### ISSUE THREAD

**Issue by 0x00err0r** [leminlimez/Nugget#184]
Traceback (most recent call last):
  File "pymobiledevice3/services/mobilebackup2.py", line 365, in device_link
  File "pymobiledevice3/services/mobilebackup2.py", line 140, in restore
  File "pymobiledevice3/services/device_link.py", line 48, in dl_loop
  File "pymobiledevice3/services/device_link.py", line 188, in receive_message
  File "pymobiledevice3/service_connection.py", line 177, in recv_plist
  File "pymobiledevice3/service_connection.py", line 147, in recv_prefixed
  File "pymobiledevice3/service_connection.py", line 141, in recvall
ConnectionAbortedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pymobiledevice3/service_connection.py", line 124, in sendall
  File "ssl.py", line 1211, in sendall
  File "ssl.py", line 1180, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "devicemanagement/device_manager.py", line 327, in apply_changes
  File "Sparserestore/restore.py", line 105, in restore_files
  File "Sparserestore/__init__.py", line 36, in perform_restore
  File "Sparserestore/__init__.py", line 27, in perform_restore
  File "pymobiledevice3/services/mobilebackup2.py", line 113, in restore
  File "contextlib.py", line 158, in __exit__
  File "pymobiledevice3/services/mobilebackup2.py", line 367, in device_link
  File "pymobiledevice3/services/device_link.py", line 191, in disconnect
  File "pymobiledevice3/service_connection.py", line 183, in send_plist
  File "pymobiledevice3/service_connection.py", line 126, in sendall
pymobiledevice3.exceptions.ConnectionTerminatedError

**Comment by realpervez** [comment]
Same error bro, let me know if you found any solution.

**Comment by leminlimez** [comment]
your ios version is not supported, read the readme
