### ISSUE TITLE
Tried all the steps but still: ConnectionTerminatedError: ConnectionTerminatedError()

### ISSUE THREAD

**Issue by realpervez** [leminlimez/Nugget#186]
I have installed all the prerequisites, I am on macOS Sequoia, MacBook Air M1 2020 Model. Tried to activate Apple Intelligence on iPhone 13 128GB model.
<img width="452" alt="Screenshot 2024-11-16 at 7 34 43 PM" src="https://github.com/user-attachments/assets/45bc33b5-c23f-4603-81d5-24b82e23809a">
Traceback (most recent call last):
  File "pymobiledevice3/services/mobilebackup2.py", line 365, in device_link
  File "pymobiledevice3/services/mobilebackup2.py", line 140, in restore
  File "pymobiledevice3/services/device_link.py", line 48, in dl_loop
  File "pymobiledevice3/services/device_link.py", line 188, in receive_message
  File "pymobiledevice3/service_connection.py", line 177, in recv_plist
  File "pymobiledevice3/service_connection.py", line 147, in recv_prefixed
  File "pymobiledevice3/service_connection.py", line 141, in recvall
ConnectionAbortedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pymobiledevice3/service_connection.py", line 124, in sendall
  File "ssl.py", line 1211, in sendall
  File "ssl.py", line 1180, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "devicemanagement/device_manager.py", line 327, in apply_changes
  File "Sparserestore/restore.py", line 105, in restore_files
  File "Sparserestore/__init__.py", line 36, in perform_restore
  File "Sparserestore/__init__.py", line 27, in perform_restore
  File "pymobiledevice3/services/mobilebackup2.py", line 113, in restore
  File "contextlib.py", line 158, in __exit__
  File "pymobiledevice3/services/mobilebackup2.py", line 367, in device_link
  File "pymobiledevice3/services/device_link.py", line 191, in disconnect
  File "pymobiledevice3/service_connection.py", line 183, in send_plist
  File "pymobiledevice3/service_connection.py", line 126, in sendall
pymobiledevice3.exceptions.ConnectionTerminatedError

**Comment by realpervez** [comment]
I am iOS 18.2 Public Beta on my phone, iPhone 13 128GB

**Comment by Phymiu** [comment]
Confirm

**Comment by leminlimez** [comment]
not supported, read the readme
