### ISSUE TITLE
iOS 18.2 183

### ISSUE THREAD

**Issue by Lixor18** [leminlimez/Nugget#269]
i updated to iOS 18.2 and i stuck on this problem
Traceback (most recent call last):
  File "devicemanagement\device_manager.py", line 80, in get_devices
  File "pymobiledevice3\lockdown.py", line 747, in create_using_usbmux
  File "pymobiledevice3\lockdown.py", line 148, in create
  File "pymobiledevice3\lockdown.py", line 550, in _handle_autopair
  File "pymobiledevice3\lockdown.py", line 67, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 378, in pair
  File "pymobiledevice3\lockdown.py", line 650, in save_pair_record
  File "pymobiledevice3\usbmux.py", line 373, in save_pair_record
  File "pymobiledevice3\usbmux.py", line 402, in _send_receive
  File "pymobiledevice3\usbmux.py", line 242, in _raise_mux_exception
pymobiledevice3.exceptions.MuxException: got an error message: {'MessageType': 'Result', 'Number': 183}

**Comment by moon-cacke** [comment]
Is 18.2 Final Release supported for Mobilegestalt with nugget ?

**Comment by Lixor18** [comment]
The point is that iOS 18.2 with nugget does not work

**Comment by Mahrad2009YP** [comment]
please give us new release faster.
🙏🙏🙏

**Comment by Starboy-263** [comment]
Nothing works on 18.2? AoD? AI?

**Comment by moon-cacke** [comment]
Anyone tested 18.2 ?

**Comment by moon-cacke** [comment]
Woooot its supported 🥹😳😳😳😳😳
https://github.com/leminlimez/Nugget/releases/tag/v4.2
did not test tho
@leminlimez thank you so much !
