### ISSUE TITLE
PyMobileDevice3Exception

### ISSUE THREAD

**Issue by brijrajparmar27** [leminlimez/Nugget#38]
```
Traceback (most recent call last):
  File "devicemanagement/device_manager.py", line 175, in apply_changes
  File "Sparserestore/restore.py", line 53, in restore_files
  File "Sparserestore/__init__.py", line 27, in perform_restore
  File "Sparserestore/__init__.py", line 20, in perform_restore
  File "pymobiledevice3/services/mobilebackup2.py", line 140, in restore
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Domain name cannot contain a slash (MBErrorDomain/205)', 'MessageName': 'Response'}
```

Device: iphone 13
IOS: 18.1
Action: Apply

**Comment by rob317** [comment]
same here
