### ISSUE TITLE
pymobiledevice3 error

### ISSUE THREAD

**Issue by Unlogisch11** [leminlimez/Nugget#66]
Hi,
i was wondering if anyone could help me. When I try to apply for my device I always get this error: 
Traceback (most recent call last):
  File "devicemanagement\device_manager.py", line 175, in apply_changes
  File "Sparserestore\restore.py", line 53, in restore_files
  File "Sparserestore\__init__.py", line 27, in perform_restore
  File "Sparserestore\__init__.py", line 20, in perform_restore
  File "pymobiledevice3\services\mobilebackup2.py", line 140, in restore
  File "pymobiledevice3\services\device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Domain name cannot contain a slash (MBErrorDomain/205)', 'MessageName': 'Response'}

![Bild_2024-10-18_135806318](https://github.com/user-attachments/assets/6ea34609-d20d-4d19-ac7d-2e6719be06b9)

**Comment by incog-geek1** [comment]
happens for me too and everyone keeps being annoying about it when I ask because they say that I'm on a unsupported version of ios or sm. but if you really want to fix it, just use misaka, its legit better

**Comment by leminlimez** [comment]
misaka will have the same issue. a fix will be released for Nugget when iOS 18.1 fully releases

**Comment by Unlogisch11** [comment]
Alright, thank you

**Comment by rmrfasterisk** [comment]
Hi, is there a way to bypass this ? Now that 18.1 is fully released.
