### ISSUE TITLE
tried multiple times but same error

### ISSUE THREAD

**Issue by Grodoo** [leminlimez/Nugget#92]
iphn 15
ios 18

Traceback (most recent call last):
  File "devicemanagement\device_manager.py", line 298, in apply_changes
  File "Sparserestore\restore.py", line 105, in restore_files
  File "Sparserestore\__init__.py", line 26, in perform_restore
  File "pymobiledevice3\services\mobilebackup2.py", line 37, in __init__
  File "pymobiledevice3\services\lockdown_service.py", line 20, in __init__
  File "pymobiledevice3\lockdown.py", line 67, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 505, in start_lockdown_service
  File "pymobiledevice3\lockdown.py", line 493, in get_service_connection_attributes
KeyError: 'EscrowBag'

Traceback (most recent call last):
  File "devicemanagement\device_manager.py", line 298, in apply_changes
  File "Sparserestore\restore.py", line 105, in restore_files
  File "Sparserestore\__init__.py", line 26, in perform_restore
  File "pymobiledevice3\services\mobilebackup2.py", line 37, in __init__
  File "pymobiledevice3\services\lockdown_service.py", line 20, in __init__
  File "pymobiledevice3\lockdown.py", line 67, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 505, in start_lockdown_service
  File "pymobiledevice3\lockdown.py", line 493, in get_service_connection_attributes
KeyError: 'EscrowBag'

Traceback (most recent call last):
  File "devicemanagement\device_manager.py", line 298, in apply_changes
  File "Sparserestore\restore.py", line 105, in restore_files
  File "Sparserestore\__init__.py", line 26, in perform_restore
  File "pymobiledevice3\services\mobilebackup2.py", line 37, in __init__
  File "pymobiledevice3\services\lockdown_service.py", line 20, in __init__
  File "pymobiledevice3\lockdown.py", line 67, in _inner_reconnect_on_remote_close
  File "pymobiledevice3\lockdown.py", line 505, in start_lockdown_service
  File "pymobiledevice3\lockdown.py", line 493, in get_service_connection_attributes
KeyError: 'EscrowBag'

**Comment by leminlimez** [comment]
nugget settings > reset pair
